### ISSUE TITLE
Doesn't actually work on Linux

### ISSUE THREAD

**Issue by Veerhan-glitch** [chethanyadav456/quickcmd#2]
![image](https://github.com/user-attachments/assets/feb61ee9-fd82-4b6a-a331-85c4da6141e8)
output of the sh RUN.sh command (to run sh files need to do sh file)

the prob is the header is windows specific

I am working on this and will soon make the pull request

**Comment by Veerhan-glitch** [comment]
@chethanyadav456 have done this so pls review, (#3 pr)

**Comment by chethanyadav456** [comment]
ok, I'll review it soon.

**Comment by chethanyadav456** [comment]
Fixed and Merged!
